### ISSUE TITLE
Add GSR logo in about app

### ISSUE THREAD

**Issue by NuttyShrimp** [ZeusWPI/hydra-android#745] opened 2023-03-14 19:12 UTC
This was a request from the AV during the AV for our budget
![image](https://user-images.githubusercontent.com/5462901/225112047-0ff3bdbc-1052-4c1b-a9fc-d93da5f1ef22.png)

**Comment by niknetniko** [comment] 2023-03-14 19:19
Duplicate of #318

**Closed by niknetniko** 2023-03-14 19:19 UTC
Labels: enhancement
